package dev.talos.runtime.verification;

public enum ProofKind {
    READBACK,
    STATIC_COHERENCE,
    STATIC_INTERACTION_GUARD,
    PARSER_EXTRACTION,
    SCHEMA_VALIDATION,
    COMMAND_EXECUTION,
    BROWSER_BEHAVIOR,
    RENDER_COMPARISON,
    OCR_EXTRACTION,
    HUMAN_ATTESTATION,
    LLM_ADVISORY
}
