package dev.talos.runtime.outcome;

public enum TruthWarningType {
    DENIED_MUTATION,
    PARTIAL_MUTATION,
    FALSE_MUTATION_CLAIM,
    INSPECT_UNDER_COMPLETION,
    SELECTOR_GROUNDED_OVERRIDE,
    STREAMING_NO_TOOL_MUTATION_REPLACED,
    STREAMING_NO_TOOL_UNGROUNDED,
    STATIC_VERIFICATION_FAILED,
    STATIC_VERIFICATION_UNAVAILABLE
}
