package dev.talos.architecture;

import com.tngtech.archunit.core.domain.Dependency;
import com.tngtech.archunit.core.domain.JavaClass;
import com.tngtech.archunit.core.domain.JavaClasses;
import com.tngtech.archunit.core.importer.ClassFileImporter;
import com.tngtech.archunit.core.importer.ImportOption;
import com.tngtech.archunit.lang.ArchRule;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Deque;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.function.Function;

import static com.tngtech.archunit.library.dependencies.SlicesRuleDefinition.slices;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Report-only package/slice cycle analysis.
 *
 * <p>This is NOT a hard guard. It imports the production {@code dev.talos}
 * bytecode through ArchUnit's Core API, slices it at four levels, and writes a
 * deterministic cycle report to
 * {@code build/reports/talos/architecture/architecture-cycle-report.md}.
 *
 * <p>Primary detection is a deterministic Tarjan strongly-connected-component
 * pass over ArchUnit-imported dependencies (manual extraction), so cycles never
 * fail the build. As an independent cross-check, ArchUnit's own
 * {@code slices().should().beFreeOfCycles()} rule is evaluated per level and its
 * {@code AssertionError} is caught and summarized rather than propagated.
 *
 * <p>Levels analyzed:
 * <ol>
 *   <li>top-level packages {@code dev.talos.(*)..}</li>
 *   <li>runtime subpackages {@code dev.talos.runtime.(*)..}</li>
 *   <li>cli subpackages {@code dev.talos.cli.(*)..}</li>
 *   <li>core subpackages {@code dev.talos.core.(*)..}</li>
 * </ol>
 */
@DisplayName("Architecture cycle report (report-only)")
class ArchitectureCycleReportTest {

    private static final String ROOT = "dev.talos";
    private static final String ROOT_PREFIX = "dev.talos.";

    private static final Path REPORT_FILE = Path.of(
            "build", "reports", "talos", "architecture", "architecture-cycle-report.md");

    @Test
    @DisplayName("generates a deterministic cycle report and never fails on detected cycles")
    void generatesCycleReport() throws IOException {
        JavaClasses classes = new ClassFileImporter()
                .withImportOption(new ImportOption.DoNotIncludeTests())
                .importPackages(ROOT);

        Edges edges = buildEdges(classes);

        StringBuilder sb = new StringBuilder();
        sb.append("# Talos Architecture Cycle Report\n\n");
        sb.append("Report-only. Generated by `dev.talos.architecture.ArchitectureCycleReportTest`. ")
                .append("Cycles here never fail the build. Content is deterministic (no timestamps). ")
                .append("Class identity is collapsed to top-level classes; only `dev.talos -> dev.talos` ")
                .append("dependencies are counted. Primary detection is a Tarjan SCC pass over ArchUnit-imported ")
                .append("dependencies; ArchUnit's own `beFreeOfCycles` rule is run per level as a caught cross-check.\n\n");

        analyzeLevel(sb, edges, classes,
                "1. Top-level packages",
                "dev.talos.(*)..",
                c -> topLevelPackage(c),
                Level.TOP);
        analyzeLevel(sb, edges, classes,
                "2. Runtime subpackages",
                "dev.talos.runtime.(*)..",
                c -> subSlice(c, "dev.talos.runtime"),
                Level.RUNTIME);
        analyzeLevel(sb, edges, classes,
                "3. CLI subpackages",
                "dev.talos.cli.(*)..",
                c -> subSlice(c, "dev.talos.cli"),
                Level.CLI);
        analyzeLevel(sb, edges, classes,
                "4. Core subpackages",
                "dev.talos.core.(*)..",
                c -> subSlice(c, "dev.talos.core"),
                Level.CORE);

        Files.createDirectories(REPORT_FILE.getParent());
        Files.writeString(REPORT_FILE, sb.toString(), StandardCharsets.UTF_8);

        assertTrue(Files.size(REPORT_FILE) > 0, "cycle report must not be empty");
    }

    // ---------------------------------------------------------------------
    // Edge extraction
    // ---------------------------------------------------------------------

    private static final class Edges {
        /** Deduped top-level-class edges "A|B" within dev.talos. */
        final TreeSet<String> classEdges = new TreeSet<>();
        /** top-level-class -> full package name. */
        final Map<String, String> packageOf = new HashMap<>();
    }

    private static Edges buildEdges(JavaClasses classes) {
        Edges e = new Edges();
        for (JavaClass jc : classes) {
            String originKey = topLevelClass(jc.getName());
            e.packageOf.putIfAbsent(originKey, jc.getPackageName());
            for (Dependency d : jc.getDirectDependenciesFromSelf()) {
                JavaClass target = d.getTargetClass();
                String targetPkg = target.getPackageName();
                if (!isTalos(targetPkg)) {
                    continue;
                }
                String targetKey = topLevelClass(target.getName());
                e.packageOf.putIfAbsent(targetKey, targetPkg);
                if (!targetKey.equals(originKey)) {
                    e.classEdges.add(originKey + "|" + targetKey);
                }
            }
        }
        return e;
    }

    // ---------------------------------------------------------------------
    // Per-level analysis
    // ---------------------------------------------------------------------

    private enum Level { TOP, RUNTIME, CLI, CORE }

    private static void analyzeLevel(StringBuilder sb, Edges edges, JavaClasses classes,
            String title, String archUnitPattern, Function<String, String> sliceOf, Level level) {
        sb.append("## ").append(title).append("\n\n");
        sb.append("Slice pattern: `").append(archUnitPattern).append("`\n\n");

        // Build slice graph from class edges in scope.
        Map<String, TreeSet<String>> adj = new TreeMap<>();
        Map<String, String> repEdge = new TreeMap<>(); // "sliceA|sliceB" -> representative class edge
        TreeSet<String> nodes = new TreeSet<>();

        for (String edge : edges.classEdges) {
            int bar = edge.indexOf('|');
            String a = edge.substring(0, bar);
            String b = edge.substring(bar + 1);
            String sa = sliceOf.apply(a);
            String sb2 = sliceOf.apply(b);
            if (sa == null || sb2 == null) {
                continue;
            }
            nodes.add(sa);
            nodes.add(sb2);
            if (!sa.equals(sb2)) {
                adj.computeIfAbsent(sa, k -> new TreeSet<>()).add(sb2);
                String pairKey = sa + "|" + sb2;
                String candidate = shortName(a) + " -> " + shortName(b);
                repEdge.merge(pairKey, candidate, (x, y) -> x.compareTo(y) <= 0 ? x : y);
            }
        }

        // Tarjan SCCs.
        List<List<String>> sccs = stronglyConnectedComponents(adj, nodes);
        List<List<String>> nonTrivial = new ArrayList<>();
        for (List<String> scc : sccs) {
            if (scc.size() > 1) {
                nonTrivial.add(scc);
            }
        }

        // Mutual 2-slice pairs.
        List<String> mutual = new ArrayList<>();
        for (String a : nodes) {
            for (String b : adj.getOrDefault(a, new TreeSet<>())) {
                if (a.compareTo(b) < 0 && adj.getOrDefault(b, new TreeSet<>()).contains(a)) {
                    mutual.add("`" + a + "` <-> `" + b + "`");
                }
            }
        }

        sb.append("- Slices in scope: ").append(nodes.size()).append("\n");
        sb.append("- Mutual 2-slice cycles: ")
                .append(mutual.isEmpty() ? "none" : String.join(", ", mutual)).append("\n");
        sb.append("- Non-trivial SCCs: ").append(nonTrivial.size())
                .append(crossCheck(classes, archUnitPattern)).append("\n\n");

        if (nonTrivial.isEmpty()) {
            sb.append("No cyclic slice groups detected at this level.\n\n");
            return;
        }

        for (List<String> scc : nonTrivial) {
            String severity = severity(level, scc);
            sb.append("### SCC {").append(String.join(", ", scc)).append("} — severity: ")
                    .append(severity).append("\n\n");
            List<String> cyclePath = findOneCycle(scc, adj);
            sb.append("- representative cycle: ")
                    .append(cyclePath.isEmpty() ? "(self-evident)" : String.join(" -> ", cyclePath)).append("\n");
            sb.append("- representative edges:\n");
            List<String> pairs = new ArrayList<>();
            for (String from : scc) {
                for (String to : adj.getOrDefault(from, new TreeSet<>())) {
                    if (scc.contains(to)) {
                        pairs.add(from + " -> " + to);
                    }
                }
            }
            pairs.sort(Comparator.naturalOrder());
            for (String p : pairs) {
                int bar = p.indexOf(" -> ");
                String pairKey = p.substring(0, bar) + "|" + p.substring(bar + 4);
                sb.append("  - `").append(p).append("`  e.g. `").append(repEdge.getOrDefault(pairKey, "?"))
                        .append("`\n");
            }
            sb.append("\n");
        }
    }

    /** Runs ArchUnit's own cycle rule and returns a caught, summarized cross-check note. */
    private static String crossCheck(JavaClasses classes, String pattern) {
        try {
            ArchRule rule = slices().matching(pattern).should().beFreeOfCycles().allowEmptyShould(true);
            rule.check(classes);
            return " (ArchUnit beFreeOfCycles cross-check: PASS — no cycles)";
        } catch (AssertionError cycleError) {
            String msg = cycleError.getMessage() == null ? "" : cycleError.getMessage();
            int cycleCount = countOccurrences(msg, "Cycle ");
            return " (ArchUnit beFreeOfCycles cross-check: cycles reported"
                    + (cycleCount > 0 ? " — " + cycleCount + " cycle group(s)" : "") + ")";
        } catch (RuntimeException unexpected) {
            return " (ArchUnit cross-check unavailable: " + unexpected.getClass().getSimpleName() + ")";
        }
    }

    private static String severity(Level level, List<String> scc) {
        switch (level) {
            case TOP:
                // Any top-level SCC is a cross-layer cycle by definition.
                return "HIGH (cross-layer top-level cycle)";
            case RUNTIME:
                if (scc.contains("policy") || scc.contains("toolcall") || scc.contains("verification")) {
                    return "HIGH (runtime policy/tool/verification cycle)";
                }
                return "MEDIUM (internal runtime cycle complicating extraction)";
            case CLI:
                if (scc.contains("modes") || scc.contains("repl")) {
                    return "MEDIUM (internal cli cycle complicating extraction)";
                }
                return "LOW (internal cli utility cycle)";
            case CORE:
                return "MEDIUM (internal core cycle complicating extraction)";
            default:
                return "UNKNOWN";
        }
    }

    // ---------------------------------------------------------------------
    // Graph helpers
    // ---------------------------------------------------------------------

    /** Finds one deterministic cycle within an SCC, returned as label path ending where it starts. */
    private static List<String> findOneCycle(List<String> scc, Map<String, TreeSet<String>> adj) {
        Set<String> sccSet = new HashSet<>(scc);
        String start = scc.get(0); // scc is sorted; smallest label
        Deque<String> path = new ArrayDeque<>();
        Set<String> onPath = new HashSet<>();
        List<String> result = new ArrayList<>();
        if (dfsCycle(start, start, adj, sccSet, path, onPath, result, true)) {
            return result;
        }
        return List.of();
    }

    private static boolean dfsCycle(String node, String start, Map<String, TreeSet<String>> adj,
            Set<String> sccSet, Deque<String> path, Set<String> onPath, List<String> result, boolean first) {
        path.addLast(node);
        onPath.add(node);
        for (String next : adj.getOrDefault(node, new TreeSet<>())) {
            if (!sccSet.contains(next)) {
                continue;
            }
            if (next.equals(start) && !first) {
                result.addAll(path);
                result.add(start);
                return true;
            }
            if (!onPath.contains(next)) {
                if (dfsCycle(next, start, adj, sccSet, path, onPath, result, false)) {
                    return true;
                }
            }
        }
        path.removeLast();
        onPath.remove(node);
        return false;
    }

    private static List<List<String>> stronglyConnectedComponents(
            Map<String, TreeSet<String>> graph, TreeSet<String> nodes) {
        Map<String, Integer> index = new HashMap<>();
        Map<String, Integer> low = new HashMap<>();
        Deque<String> stack = new ArrayDeque<>();
        Set<String> onStack = new HashSet<>();
        int[] counter = {0};
        List<List<String>> result = new ArrayList<>();
        for (String n : nodes) {
            if (!index.containsKey(n)) {
                strongConnect(n, graph, index, low, stack, onStack, counter, result);
            }
        }
        result.sort(Comparator.comparing(scc -> scc.get(0)));
        return result;
    }

    private static void strongConnect(String root, Map<String, TreeSet<String>> graph, Map<String, Integer> index,
            Map<String, Integer> low, Deque<String> stack, Set<String> onStack, int[] counter,
            List<List<String>> result) {
        Deque<String> callStack = new ArrayDeque<>();
        Deque<Integer> iterStack = new ArrayDeque<>();
        Map<String, List<String>> neighborCache = new LinkedHashMap<>();
        callStack.push(root);
        iterStack.push(0);
        while (!callStack.isEmpty()) {
            String node = callStack.peek();
            int i = iterStack.pop();
            if (i == 0) {
                index.put(node, counter[0]);
                low.put(node, counter[0]);
                counter[0]++;
                stack.push(node);
                onStack.add(node);
                List<String> neighbors = new ArrayList<>(graph.getOrDefault(node, new TreeSet<>()));
                neighbors.sort(Comparator.naturalOrder());
                neighborCache.put(node, neighbors);
            }
            List<String> neighbors = neighborCache.get(node);
            boolean recursed = false;
            while (i < neighbors.size()) {
                String w = neighbors.get(i);
                i++;
                if (!index.containsKey(w)) {
                    iterStack.push(i);
                    callStack.push(w);
                    iterStack.push(0);
                    recursed = true;
                    break;
                } else if (onStack.contains(w)) {
                    low.put(node, Math.min(low.get(node), index.get(w)));
                }
            }
            if (recursed) {
                continue;
            }
            if (low.get(node).equals(index.get(node))) {
                List<String> scc = new ArrayList<>();
                String w;
                do {
                    w = stack.pop();
                    onStack.remove(w);
                    scc.add(w);
                } while (!w.equals(node));
                scc.sort(Comparator.naturalOrder());
                result.add(scc);
            }
            callStack.pop();
            if (!callStack.isEmpty()) {
                String parent = callStack.peek();
                low.put(parent, Math.min(low.get(parent), low.get(node)));
            }
        }
    }

    // ---------------------------------------------------------------------
    // Naming helpers
    // ---------------------------------------------------------------------

    private static boolean isTalos(String pkg) {
        return pkg != null && (pkg.equals(ROOT) || pkg.startsWith(ROOT_PREFIX));
    }

    private static String stripArray(String name) {
        String n = name;
        while (n.startsWith("[")) {
            n = n.substring(1);
        }
        if (n.startsWith("L") && n.endsWith(";")) {
            n = n.substring(1, n.length() - 1);
        }
        while (n.endsWith("[]")) {
            n = n.substring(0, n.length() - 2);
        }
        return n;
    }

    private static String topLevelClass(String name) {
        String n = stripArray(name);
        int dollar = n.indexOf('$');
        return dollar < 0 ? n : n.substring(0, dollar);
    }

    /** Top-level package label, e.g. "runtime". Null if outside dev.talos. */
    private static String topLevelPackage(String classKey) {
        return segmentAfter(classKey, ROOT);
    }

    /** Subslice label under a base package, e.g. base "dev.talos.runtime" -> "policy"; root -> "(root)". */
    private static String subSlice(String classKey, String base) {
        if (classKey == null) {
            return null;
        }
        if (!classKey.startsWith(base + ".")) {
            return null;
        }
        String rest = classKey.substring((base + ".").length());
        int dot = rest.indexOf('.');
        if (dot < 0) {
            // class sits directly in the base package
            return "(root)";
        }
        return rest.substring(0, dot);
    }

    /** Returns the first package segment after the given root prefix, derived from a class FQN. */
    private static String segmentAfter(String classKey, String rootPkg) {
        if (classKey == null || !classKey.startsWith(rootPkg + ".")) {
            return null;
        }
        String rest = classKey.substring((rootPkg + ".").length());
        int dot = rest.indexOf('.');
        // rest is like "cli.modes.Foo" -> first segment "cli"
        return dot < 0 ? rest : rest.substring(0, dot);
    }

    private static String shortName(String fqcn) {
        return fqcn.startsWith(ROOT_PREFIX) ? fqcn.substring(ROOT_PREFIX.length()) : fqcn;
    }

    private static int countOccurrences(String haystack, String needle) {
        int count = 0;
        int idx = 0;
        while ((idx = haystack.indexOf(needle, idx)) >= 0) {
            count++;
            idx += needle.length();
        }
        return count;
    }
}
