package dev.talos.architecture;

import com.tngtech.archunit.core.domain.Dependency;
import com.tngtech.archunit.core.domain.JavaAccess;
import com.tngtech.archunit.core.domain.JavaCall;
import com.tngtech.archunit.core.domain.JavaClass;
import com.tngtech.archunit.core.domain.JavaClasses;
import com.tngtech.archunit.core.importer.ClassFileImporter;
import com.tngtech.archunit.core.importer.ImportOption;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Report-only access report for the Talos execution-harness control spine.
 *
 * <p>This deliberately does NOT build a whole-project method-call graph (that is
 * noise). It imports the production {@code dev.talos} bytecode through ArchUnit's
 * Core API and, for a fixed set of runtime-control "spine" classes, reports
 * class-level fan-in/fan-out and (where ArchUnit exposes it) method/constructor
 * call counts.
 *
 * <p>It is purely report-only: it never fails the build for high fan-in/fan-out
 * and only asserts that the report file was written. Output is deterministic
 * (no timestamps) and capped to top-N entries per section.
 */
@DisplayName("Harness-spine access report (report-only)")
class ArchitectureSpineAccessReportTest {

    private static final String ROOT = "dev.talos";
    private static final String ROOT_PREFIX = "dev.talos.";
    private static final int TOP_N = 15;

    private static final Path REPORT_FILE = Path.of(
            "build", "reports", "talos", "architecture", "harness-spine-access-report.md");

    /** Spine target classes (FQN) paired with a documented role hint. */
    private static final Map<String, String> TARGETS = new LinkedHashMap<>();

    static {
        TARGETS.put("dev.talos.cli.modes.AssistantTurnExecutor", "orchestration hub");
        TARGETS.put("dev.talos.runtime.ToolCallLoop", "tool execution hub");
        TARGETS.put("dev.talos.runtime.toolcall.ToolCallRepromptStage", "tool execution hub");
        TARGETS.put("dev.talos.runtime.toolcall.ToolSurfacePlanner", "tool execution hub");
        TARGETS.put("dev.talos.runtime.turn.CurrentTurnPlan", "context/plan hub");
        TARGETS.put("dev.talos.runtime.task.TaskContractResolver", "policy hub");
        TARGETS.put("dev.talos.runtime.policy.ActionObligationPolicy", "policy hub");
        TARGETS.put("dev.talos.runtime.policy.EvidenceObligationPolicy", "policy hub");
        TARGETS.put("dev.talos.runtime.policy.EvidenceObligationVerifier", "verifier");
        TARGETS.put("dev.talos.runtime.verification.StaticTaskVerifier", "verifier");
        TARGETS.put("dev.talos.cli.modes.ExecutionOutcome", "outcome value/model");
        TARGETS.put("dev.talos.core.context.ConversationManager", "context hub");
    }

    @Test
    @DisplayName("generates a deterministic harness-spine access report and never fails on fan-in/out")
    void generatesSpineAccessReport() throws IOException {
        JavaClasses classes = new ClassFileImporter()
                .withImportOption(new ImportOption.DoNotIncludeTests())
                .importPackages(ROOT);

        StringBuilder sb = new StringBuilder();
        sb.append("# Talos Execution-Harness Spine Access Report\n\n");
        sb.append("Report-only. Generated by `dev.talos.architecture.ArchitectureSpineAccessReportTest`. ")
                .append("Scoped to the runtime-control spine only (no whole-project call graph). ")
                .append("Content is deterministic (no timestamps); each section is capped to the top ")
                .append(TOP_N).append(" entries. Counts are restricted to `dev.talos -> dev.talos` ")
                .append("relationships. Class identity is collapsed to top-level classes (inner classes ")
                .append("folded into their enclosing type).\n\n");
        sb.append("Method/constructor call counts come from ArchUnit `getCallsFromSelf()` / ")
                .append("`getCallsToSelf()`. Where ArchUnit cannot resolve a call to imported bytecode ")
                .append("(e.g. JDK or reflective calls), it is omitted; in that case the class-level ")
                .append("dependency sections remain authoritative.\n\n");

        for (Map.Entry<String, String> entry : TARGETS.entrySet()) {
            renderTarget(sb, classes, entry.getKey(), entry.getValue());
        }

        Files.createDirectories(REPORT_FILE.getParent());
        Files.writeString(REPORT_FILE, sb.toString(), StandardCharsets.UTF_8);

        assertTrue(Files.size(REPORT_FILE) > 0, "spine access report must not be empty");
    }

    // ---------------------------------------------------------------------

    private static void renderTarget(StringBuilder sb, JavaClasses classes, String fqn, String roleHint) {
        sb.append("## ").append(shortName(fqn)).append("\n\n");
        sb.append("- FQN: `").append(fqn).append("`\n");
        sb.append("- documented role: ").append(roleHint).append("\n");

        if (!classes.contain(fqn)) {
            sb.append("- status: NOT FOUND in imported production classes (skipped)\n\n");
            return;
        }
        JavaClass self = classes.get(fqn);

        // 1. Direct class dependencies from self (fan-out), grouped by target top-level class.
        Map<String, Integer> depsFrom = new TreeMap<>();
        for (Dependency d : self.getDirectDependenciesFromSelf()) {
            String tgtPkg = d.getTargetClass().getPackageName();
            if (!isTalos(tgtPkg)) {
                continue;
            }
            String key = topLevelClass(d.getTargetClass().getName());
            if (!key.equals(topLevelClass(fqn))) {
                depsFrom.merge(key, 1, Integer::sum);
            }
        }

        // 2. Direct class dependencies to self (fan-in), grouped by origin top-level class.
        Map<String, Integer> depsTo = new TreeMap<>();
        for (Dependency d : self.getDirectDependenciesToSelf()) {
            String srcPkg = d.getOriginClass().getPackageName();
            if (!isTalos(srcPkg)) {
                continue;
            }
            String key = topLevelClass(d.getOriginClass().getName());
            if (!key.equals(topLevelClass(fqn))) {
                depsTo.merge(key, 1, Integer::sum);
            }
        }

        // 3. Method/constructor calls FROM self -> "Owner#member" within dev.talos.
        Map<String, Integer> callsFrom = new TreeMap<>();
        Map<String, Integer> calleeClasses = new TreeMap<>();
        List<JavaCall<?>> callsFromSelf = new ArrayList<>();
        callsFromSelf.addAll(self.getMethodCallsFromSelf());
        callsFromSelf.addAll(self.getConstructorCallsFromSelf());
        for (JavaCall<?> call : callsFromSelf) {
            JavaClass owner = call.getTargetOwner();
            if (!isTalos(owner.getPackageName())) {
                continue;
            }
            String ownerKey = topLevelClass(owner.getName());
            if (ownerKey.equals(topLevelClass(fqn))) {
                continue;
            }
            callsFrom.merge(shortName(ownerKey) + "#" + call.getTarget().getName(), 1, Integer::sum);
            calleeClasses.merge(ownerKey, 1, Integer::sum);
        }

        // 4. Method/constructor calls TO self -> "Caller#member" within dev.talos.
        Map<String, Integer> callsTo = new TreeMap<>();
        Map<String, Integer> callerClasses = new TreeMap<>();
        List<JavaCall<?>> callsToSelf = new ArrayList<>();
        for (JavaAccess<?> access : self.getAccessesToSelf()) {
            if (access instanceof JavaCall<?> call) {
                callsToSelf.add(call);
            }
        }
        for (JavaCall<?> call : callsToSelf) {
            JavaClass origin = call.getOriginOwner();
            if (!isTalos(origin.getPackageName())) {
                continue;
            }
            String originKey = topLevelClass(origin.getName());
            if (originKey.equals(topLevelClass(fqn))) {
                continue;
            }
            callsTo.merge(shortName(originKey) + "#" + call.getOrigin().getName(), 1, Integer::sum);
            callerClasses.merge(originKey, 1, Integer::sum);
        }

        sb.append("- fan-out (distinct dev.talos classes depended on): ").append(depsFrom.size()).append("\n");
        sb.append("- fan-in (distinct dev.talos classes depending on this): ").append(depsTo.size()).append("\n\n");

        sb.append("**Top callees (classes this calls into):** ").append(formatClassCounts(calleeClasses)).append("\n\n");
        sb.append("**Top callers (classes calling into this):** ").append(formatClassCounts(callerClasses)).append("\n\n");

        appendCountSection(sb, "1. Direct class dependencies from self (fan-out)", depsFrom, true);
        appendCountSection(sb, "2. Direct class dependencies to self (fan-in)", depsTo, true);
        appendCountSection(sb, "3. Method/constructor calls from self", callsFrom, false);
        appendCountSection(sb, "4. Method/constructor calls to self", callsTo, false);

        sb.append("**Interpretation:** ").append(roleHint).append(". ")
                .append(godObjectAssessment(depsFrom.size(), depsTo.size(),
                        callsFromSelf.size(), callsToSelf.size()))
                .append("\n\n");
        sb.append("---\n\n");
    }

    private static String godObjectAssessment(int fanOut, int fanIn, int callsFrom, int callsTo) {
        // Heuristic, report-only. Not a hard gate.
        boolean wideOut = fanOut >= 30;
        boolean wideIn = fanIn >= 30;
        boolean heavyCalls = callsFrom >= 150;
        if (wideOut && wideIn) {
            return "Possible god-object risk: high fan-out AND high fan-in — both an orchestrator and a "
                    + "magnet; review for responsibility split.";
        }
        if (wideOut && heavyCalls) {
            return "Possible god-object risk: high fan-out with heavy outgoing calls — likely doing too "
                    + "much; candidate for delegation/extraction.";
        }
        if (wideIn) {
            return "Well-used hub: high fan-in but contained fan-out — acceptable as a shared "
                    + "type/contract if it stays thin.";
        }
        if (wideOut) {
            return "Coordinator with wide fan-out but modest fan-in — acceptable for an orchestrator; "
                    + "watch growth.";
        }
        return "Reasonably contained: fan-in and fan-out are within moderate bounds.";
    }

    // ---------------------------------------------------------------------
    // formatting helpers
    // ---------------------------------------------------------------------

    private static void appendCountSection(StringBuilder sb, String title, Map<String, Integer> counts,
            boolean wrapCode) {
        sb.append("**").append(title).append("** (")
                .append(counts.size()).append(" total");
        if (counts.size() > TOP_N) {
            sb.append(", showing top ").append(TOP_N);
        }
        sb.append(")\n\n");
        if (counts.isEmpty()) {
            sb.append("- none\n\n");
            return;
        }
        List<Map.Entry<String, Integer>> sorted = new ArrayList<>(counts.entrySet());
        sorted.sort(Comparator
                .comparingInt((Map.Entry<String, Integer> e) -> e.getValue()).reversed()
                .thenComparing(Map.Entry::getKey));
        int limit = Math.min(TOP_N, sorted.size());
        for (int i = 0; i < limit; i++) {
            Map.Entry<String, Integer> e = sorted.get(i);
            sb.append("- ");
            if (wrapCode) {
                sb.append('`').append(e.getKey()).append('`');
            } else {
                sb.append('`').append(e.getKey()).append('`');
            }
            sb.append(" — ").append(e.getValue()).append('\n');
        }
        sb.append('\n');
    }

    private static String formatClassCounts(Map<String, Integer> counts) {
        if (counts.isEmpty()) {
            return "none";
        }
        List<Map.Entry<String, Integer>> sorted = new ArrayList<>(counts.entrySet());
        sorted.sort(Comparator
                .comparingInt((Map.Entry<String, Integer> e) -> e.getValue()).reversed()
                .thenComparing(Map.Entry::getKey));
        int limit = Math.min(TOP_N, sorted.size());
        List<String> parts = new ArrayList<>();
        for (int i = 0; i < limit; i++) {
            Map.Entry<String, Integer> e = sorted.get(i);
            parts.add("`" + shortName(e.getKey()) + "` (" + e.getValue() + ")");
        }
        return String.join(", ", parts);
    }

    // ---------------------------------------------------------------------
    // naming helpers
    // ---------------------------------------------------------------------

    private static boolean isTalos(String pkg) {
        return pkg != null && (pkg.equals(ROOT) || pkg.startsWith(ROOT_PREFIX));
    }

    private static String stripArray(String name) {
        String n = name;
        while (n.startsWith("[")) {
            n = n.substring(1);
        }
        if (n.startsWith("L") && n.endsWith(";")) {
            n = n.substring(1, n.length() - 1);
        }
        while (n.endsWith("[]")) {
            n = n.substring(0, n.length() - 2);
        }
        return n;
    }

    private static String topLevelClass(String name) {
        String n = stripArray(name);
        int dollar = n.indexOf('$');
        return dollar < 0 ? n : n.substring(0, dollar);
    }

    private static String shortName(String fqcn) {
        return fqcn.startsWith(ROOT_PREFIX) ? fqcn.substring(ROOT_PREFIX.length()) : fqcn;
    }
}
